spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/identity-service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: identity-service

server:
  port: 8088

jwt:
  signerKey: "YGvocgX6OuERsoVBDzsgvCrgL+Mc/zOlpq5NQJjfUMLUPSnviRxV7VkceAV4G4VF"

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
