---
version: '3.7'
services:

  inventory-db:
    image: mysql:8.0
    container_name: inventory-service
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory-service
    ports:
      - "3307:3306"
    volumes:
      - inventory-db-data:/var/lib/mysql

  order-db:
    image: mysql:8.0
    container_name: order-service
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order-service
    ports:
      - "3308:3306"
    volumes:
      - order-db-data:/var/lib/mysql

  product-db:
    image: mysql:8.0
    container_name: product-service
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product-service
    ports:
      - "3309:3306"
    volumes:
      - product-db-data:/var/lib/mysql

  identity-db:
    image: mysql:8.0
    container_name: identity-service
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity-service
    ports:
      - "3305:3306"
    volumes:
      - identity-db-data:/var/lib/mysql

  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER


volumes:
  inventory-db-data:
  order-db-data:
  product-db-data:
  identity-db-data: