spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/product-service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: product-service

server:
  port: 8083


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka